name: "Install dependencies"
description: "Install app pnpm dependencies"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 6.32.9
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'pnpm'
        cache-dependency-path: '**/pnpm-lock.yaml'
    - name: Pnpm install dependencies
      run: pnpm install --frozen-lockfile