name: Animal Farm NodeJS CI
on:
  push:
    branches:
      - develop
      - feat/ci
  pull_request:
    types: [opened, reopened, edited]
    branches:
      - main
      - develop
jobs:
  build-web:
    name: "Build web application"
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/composite-action
  build-api-gateway:
    name: 'Build api gateway'
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/composite-action
  test-api:
    name: "Testing api"
    needs: build-api-gateway
    runs-on: ubuntu-latest
    steps:
      - run: echo Testing api
  test-web:
    name: "Testing web"
    needs: build-web
    runs-on: ubuntu-latest
    steps:
      - run: echo Testing web