name: Animal Farm NodeJS CI
on:
  push:
    branches:
      - develop
      - feat/ci
  pull_request:
    types: [opened, reopened, edited]
    branches:
      - main
      - develop
jobs:
  build-web:
  build-api:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/composite-action
  test-api:
    needs: build-api
  test-web:
    needs: build-web