name: Building, Testing and Deploying project
on:
  push:
    branches:
      - develop
      - feat/ci
  pull_request:
    types: [opened, reopened, edited]
    branches:
      - main
      - develop
jobs:
  build-web:
    name: "Build web application"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - name: Pnpm install dependencies
        working-directory: ./app/frontend
        run: pnpm install --frozen-lockfile
      - name: Build web app
        working-directory: ./app/frontend
        run: pnpm build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: web-production
          retention-days: 7
          path: app/frontend/.next
  build-api-gateway:
    name: 'Build api gateway'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - name: Install dependencies
        working-directory: ./app/api/gateway
        run: pnpm install --frozen-lockfile
      - name: Build api
        working-directory: ./app/api/gateway
        run: pnpm build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
         name: api-gateway-production
         retention-days: 7
         path: app/api/gateway/dist
  test-api:
    name: "Testing api"
    needs: build-api-gateway
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ./app/api/gateway
      - name: pnpm test
        working-directory: ./app/api/gateway
        run: pnpm test
  test-web:
    name: "Testing web"
    needs: build-web
    runs-on: ubuntu-latest
    steps:
      - run: echo Testing web
  build-services:
    name: "Build microservice"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        services: [
          {name: "User", folder: "./app/api/user"},
          {name: "Events", folder: "./app/api/events"}
        ]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - run: "echo Build ${{ matrix.services.name }} microservice - ${{ matrix.services.folder }}"
      - name: "Building dependencies"
        working-directory: ${{ matrix.services.folder }}
        run: pnpm install --frozen-lockfile
      - name: "Build service"
        working-directory: ${{ matrix.services.folder }}
        run: pnpm build
  test-services:
    name: "Build microservice"
    runs-on: ubuntu-latest
    needs: [build-services]
    strategy:
      matrix:
        services: [
          { name: "User", folder: "./app/api/user" },
          { name: "Events", folder: "./app/api/events" }
        ]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - run: "echo Build ${{ matrix.services.name }} microservice - ${{ matrix.services.folder }}"
      - name: "Building dependencies"
        working-directory: ${{ matrix.services.folder }}
        run: pnpm install --frozen-lockfile
      - name: "Build service"
        working-directory: ${{ matrix.services.folder }}
        run: pnpm test
  deploy-services:
    name: "Deploy microservices"
    needs: [build-services, test-services]
    runs-on: ubuntu-latest
    steps:
      - run: echo Deploy microservices ...
  deploy-apps:
    name: "Deploy applications (frontend and api-gateway)"
    needs: [test-api, test-web, deploy-services]
    runs-on: ubuntu-latest
    steps:
      - run: echo Deploy applications ...
